{
 "title": "Reef Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Reef System (Recent)",
   "type": "graph",
   "description": "Reef system monitoring",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Display Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_display_tank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "display_tank" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "ds/28ffe48d011703" }
     ]
    },
    {
     "alias": "Sump In",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_intake' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sump_intake" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "ds/28ff6cf5011704" }
     ]
    },
    {
     "alias": "Water Stability Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_discharge' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "water_stability_tank" }
     ]
    },
    {
     "alias": "Salt Water Mix Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_discharge' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mixtank" }
     ]
    }
   ]
  },
  {
   "title": "Reef System (Historical)",
   "type": "graph",
   "description": "Reef system monitoring",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "fahrenheit", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Display Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"val\") FROM \"fahrenheit\" WHERE (\"name\" = 'display_tank' OR \"device\" = 'ds/28ffe48d011703') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "display_tank" }
     ]
    },
    {
     "alias": "Sump In",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_intake' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sump_intake" }
     ]
    },
    {
     "alias": "Water Stability Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_discharge' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "water_stability_tank" }
     ]
    },
    {
     "alias": "Reefwater Mix",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_discharge' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mixtank" }
     ]
    }
   ]
  },
  {
   "title": "Water Mix Prep",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "fahrenheit", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Display Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"val\") FROM \"fahrenheit\" WHERE (\"name\" = 'display_tank') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "display_tank" }
     ]
    },
    {
     "alias": "Water Stability Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"val\") FROM \"fahrenheit\" WHERE (\"name\" = 'display_tank') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "water_stability_tank" }
     ]
    },
    {
     "alias": "Mix Tank (top)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_mixtank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mixtank_top" }
     ]
    },
    {
     "alias": "Mix Tank (mid)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_mixtank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mixtank_midpoint" }
     ]
    },
    {
     "alias": "Mix Tank (bottom)",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_mixtank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mixtank" }
     ]
    }
   ]
  },
  {
   "title": "Reef Misc",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "fahrenheit", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Remote PCB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_mixtank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "reef:display:pcb" }
     ]
    },
    {
     "alias": "Cabinet Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_display_tank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "display_tank:cabinet" }
     ]
    },
    {
     "alias": "Sump Ambient Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_display_tank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sump_ambient" }
     ]
    },
    {
     "alias": "Display Tank Ambient",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "display_tank_ambient" }
     ]
    },
    {
     "alias": "Lab Enclosure Alpha",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_display_tank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "lab enclosure alpha" }
     ]
    },
    {
     "alias": "Cabinet RH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "relhum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "display_tank:cabinet" }
     ]
    }
   ]
  }
 ]
}