{
 "title": "Wiss Landing",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Wiss Landing Environmental",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Attic",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_basement2' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "attic_equip_room" }
     ]
    },
    {
     "alias": "Attic South Exterior Wall",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "attic_south_exterior" }
     ]
    },
    {
     "alias": "Attic Roof South",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "attic_south_roof" }
     ]
    },
    {
     "alias": "Lab Enclosure Alpha",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_basement2' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "lab enclosure alpha" }
     ]
    },
    {
     "alias": "Exterior NE",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT median(\"val\") FROM \"celsius\" WHERE (\"friendly_name\" = 'exterior_ne') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "exterior_ne" }
     ]
    },
    {
     "alias": "Lab Enclosure Beta",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"humidity\" WHERE \"sensor\" = 'hs_basement' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "i2c/lab-ledge.00.sht31" }
     ]
    },
    {
     "alias": "Exterior SE",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_exterior' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "exterior_se" }
     ]
    },
    {
     "alias": "Laundry Room Ambient",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_basement2' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "laundry_room" }
     ]
    },
    {
     "alias": "Sump Ambient",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_basement' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sump_ambient" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "ds/28fff20f721603" }
     ]
    },
    {
     "alias": "Bistro",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "bistro:onboard.hires" }
     ]
    },
    {
     "alias": "Attic RH",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relative_humidity",
     "query": "SELECT mean(\"value\") FROM \"humidity\" WHERE \"sensor\" = 'hs_basement' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "attic_equip_room" }
     ]
    },
    {
     "alias": "Lab Enclosure Alpha RH",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relative_humidity",
     "query": "SELECT mean(\"value\") FROM \"humidity\" WHERE \"sensor\" = 'hs_basement' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "basement_equip_room" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "lab enclosure alpha" }
     ]
    },
    {
     "alias": "Bistro RH",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relative_humidity",
     "query": "SELECT mean(\"value\") FROM \"humidity\" WHERE \"sensor\" = 'hs_basement' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "i2c/bistro.02.sht31" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "bistro" }
     ]
    },
    {
     "alias": "Lab Enclosure Beta RH",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "relative_humidity",
     "query": "SELECT mean(\"value\") FROM \"humidity\" WHERE \"sensor\" = 'hs_basement' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "i2c/lab-ledge.00.sht31" }
     ]
    },
    {
     "alias": "Attic South Exterior Wall",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor",
     "select": [
      [
       { "params": [ "temp_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "lab-ledge:pcb" }
     ]
    }
   ]
  },
  {
   "title": "Reef System",
   "type": "graph",
   "description": "Reef system monitoring",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Display Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_display_tank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "display_tank" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "ds/28ffe48d011703" }
     ]
    },
    {
     "alias": "Sump In",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_intake' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sump_intake" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "ds/28ff6cf5011704" }
     ]
    },
    {
     "alias": "Sump Out",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_discharge' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "sump_discharge" }
     ]
    },
    {
     "alias": "Reefwater Mix",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_sump_discharge' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mixtank" }
     ]
    }
   ]
  },
  {
   "title": "Water Mix Prep",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "fahrenheit", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Mix Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_mixtank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "mixtank" }
     ]
    },
    {
     "alias": "Display Tank",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_display_tank' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "display_tank" }
     ]
    }
   ]
  },
  {
   "title": "HVAC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Dryer Exhaust",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_dryer_exhaust' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "dryer_exhaust" }
     ]
    },
    {
     "alias": "Washer Drain",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_supply' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "washer_drain" }
     ]
    },
    {
     "alias": "HVAC1 Return",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_return' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "hvac1_return" }
     ]
    },
    {
     "alias": "HVAC1 Supply",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_supply' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "hvac1_supply" }
     ]
    },
    {
     "alias": "HVAC1 Liquid Line",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_supply' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "hvac1_liquid_line" }
     ]
    },
    {
     "alias": "HVAC1 Suction Line",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_supply' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "hvac1_suction_line" }
     ]
    },
    {
     "alias": "HVAC2 Return",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_return' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "hvac2_return" }
     ]
    },
    {
     "alias": "HVAC2 Supply",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_return' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "hvac2_supply" }
     ]
    },
    {
     "alias": "HVAC2 Suction Side",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_return' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ds/28ff5e18721603" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "hvac2_low_side" }
     ]
    },
    {
     "alias": "HVAC2 Liquid Side",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"temperature\" WHERE \"sensor\" = 'ts_hvac_supply' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ds/28ff43a3701604" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "hvac2_high_side" }
     ]
    }
   ]
  },
  {
   "title": "Updates and Latencies",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "alias": "External Update µs",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "run_metric",
     "query": "SELECT mean(\"value\") FROM \"duration\" WHERE \"loop\" = 'last_update_ms' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(0)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "janice" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "external_update" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "prod" }
     ]
    },
    {
     "alias": "Round Trip Latency",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "run_metric",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "sw_cmd_rt_latency_us" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "prod" }
     ]
    },
    {
     "alias": "Dev Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "run_metric",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "dev_latency" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "prod" }
     ]
    },
    {
     "alias": "Process Inbound MQTT Message µs",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "run_metric",
     "query": "SELECT mean(\"value\") FROM \"duration\" WHERE \"loop\" = 'last_update_ms' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(0)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "janice" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "mqtt_process_inbound_msg_us" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "prod" }
     ]
    },
    {
     "alias": "Recv  MQTT Message µs",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "run_metric",
     "query": "SELECT mean(\"value\") FROM \"duration\" WHERE \"loop\" = 'last_update_ms' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(0)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "janice" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "mqtt_recv_msg_us" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "prod" }
     ]
    },
    {
     "alias": "Send  MQTT Message µs",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "run_metric",
     "query": "SELECT mean(\"value\") FROM \"duration\" WHERE \"loop\" = 'last_update_ms' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(0)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "janice" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "mqtt_pub_msg_us" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "prod" }
     ]
    },
    {
     "alias": "Pub Switch Command µs",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "run_metric",
     "query": "SELECT mean(\"value\") FROM \"duration\" WHERE \"loop\" = 'last_update_ms' AND \"node\" = 'mcp' AND \"env\" = 'prod' AND $timeFilter GROUP BY time($interval) fill(0)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=", "value": "janice" },
      { "condition": "AND", "key": "metric", "operator": "=", "value": "sw_cmd" },
      { "condition": "AND", "key": "env", "operator": "=", "value": "prod" }
     ]
    }
   ]
  }
 ]
}