[meta]
name = "ds i2c"
# the description is not sent to the Host
# rather, it is used by Sally to log the profile sent to the host
description = "dalsemi and i2c"
version = 1

[host]
report_ms = 17_000

[ota]
base_url = "https://www.wisslanding.com/sally/firmware"
valid_ms = 59_000

# the following configurations are reasonable for dalsemi, i2c, pwm and dmx
# the engine is started only when the configuration is present

[dalsemi]
report = {stack = 4096, pri = 5, send_ms = 30_000, loops_per_discover = 10 }
command = {stack = 4096, pri = 14}

[i2c]
report = {stack = 4096, pri = 5, send_ms = 13_000, loops_per_discover = 10 }
command = {stack = 4096, pri = 14}
