# default profile assigned to newly created hosts or
# when assigned profile does not exist

# provides the minimal configuration required for a Host
# and does not start any Engines or other functionality
[meta]
name = "generic"
# the description is not sent to the Host
# rather, it is used by Sally to log the profile sent to the host
description = "simple, no engines"
version = 1

[host]
report_ms = 7_000

[ota]
base_url = "https://www.wisslanding.com/sally/firmware"
valid_ms = 59_000
