[meta]
name = "lightdesk"
# the description is not sent to the Host
# rather, it is used by Sally to log the profile sent to the host
description = "lightdesk only"
version = 1

[host]
base_url = "https://www.wisslanding.com/sally/firmware"
report_ms = 7_000

[lightdesk]
dmx_port = 48005
idle_shutdown_ms = 600_000
idle_check_ms = 1000
